name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://bethtest-3.pact.dius.com.au
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BRANCH: ${{ github.ref }}


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: npm i
      - name: Test
        run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make test

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    - uses: actions/checkout@v2
    steps:
      - name: Can I deploy?
        run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make can_i_deploy

  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make deploy
        if: github.ref == 'refs/heads/master'
